### PR TITLE
Change RSpec --format option from 'specdoc' to 'documentation'

### PR DESCRIPTION
**Pull request by bturnbull**
Using gem-this generated Rakefiles with RSpec 2.6 throws an ArgumentError exception trying to use the specdoc formatter.

```
.../rspec-core-2.6.4/lib/rspec/core/configuration.rb:281:in `add_formatter': Formatter 'specdoc' unknown - maybe you meant 'documentation' or 'progress'?. (ArgumentError)
```

This pull request makes the change in the Rakefile ERB template to use the documentation formatter.

### CODE REVIEW

**Comment by lazyatom** [comment]
Is the `documentation` format just a new version of `specdoc`? I don't actually use RSpec, so I'm not sure exactly what changes during its evolution. If it's equivalent, I'd be happy to merge this.

**Comment by rentalcustard** [comment]
Yep, documentation is the new name for specdoc.

**Comment by bturnbull** [comment]
What mortice said. ;)

**Comment by lazyatom** [comment]
Boom, done. I'll push a new version to rubygems.org too.

**Comment by lazyatom** [comment]
I've just pushed 0.3.7, which includes this fix. Thanks!

**Comment by bturnbull** [comment]
Glad to help -- gem-this is a perfect fit for my gem dev workflow.

**Pull request merged**
